use_frameworks!

platform :ios, '8.0'

target 'SZPublicPodTest_Example' do
  pod 'SZPublicPodTest', :path => '../'

  target 'SZPublicPodTest_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
