# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11
language: objective-c

#env:
#  global:
#    - LANG=en_US.UTF-8
#    - LC_ALL=en_US.UTF-8
#    - XCODE_WORKSPACE=Example/SZPublicPodTest.xcworkspace
#    - DESTINATION="OS=12.0,name=iPhone XS"
#  matrix:
#    - SCHEME="SZPublicPodTest-Example"
#
#before_install:
#  - gem install xcpretty --no-document --quiet
#  - gem install cocoapods --pre --no-document --quiet
#  - pod install --project-directory=Example
#
#script:
##- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/SZPublicPodTest.xcworkspace -scheme SZPublicPodTest-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
##- pod lib lint
#- set -o pipefail
#- xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
##- xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
#- pod lib lint --allow-warnings
